spring.application.name=beemate

spring.datasource.url=jdbc:sqlserver://sql5113.site4now.net:1433;databaseName=db_ac7b68_beemate;trustServerCertificate=true;
spring.datasource.username=db_ac7b68_beemate_admin
spring.datasource.password=C@ominh123

#spring.datasource.url=jdbc:mysql://avnadmin:AVNS_Uu9PzbG6ISnjYdMQT7I@mysql-3acd6a3b-minhbc-0110.g.aivencloud.com:25856/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_Uu9PzbG6lSnjYdMQT7I
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# --- C?U HÌNH SQL SERVER ---
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=beemate;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=sa
#spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
# ---------------------------

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG
spring.web.resources.static-locations=classpath:/static/

spring.web.locale=vi_VN
spring.web.locale-resolver=fixed

spring.mvc.format.date=dd/MM/yyyy
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jackson.serialization.fail-on-empty-beans=false

logging.level.root=WARN
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.transaction=DEBUG

server.error.include-message=always

cloudinary.cloud-name=dygj3spwt
cloudinary.api-key=979376284138992
cloudinary.api-secret=HdMhK5dGHtNN79JrPDTeRyntxm8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

momo.partnerCode=MOMOLRJZ20181206
momo.accessKey=mTCKt9W3eU1m39TW
momo.secretKey=SetA5RDnLHvt51AULf51DyauxUo3kDU6
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.returnUrl=http://localhost:8080/admin
momo.notifyUrl=https://finless-nongrievous-coralie.ngrok-free.dev/api/pos/momo-callback

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenducvu1594@gmail.com
spring.mail.password=allmjetimuiteznq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

vnpay.tmnCode=UP4FF5Y5
vnpay.hashSecret=K2QZA10211BVOTB4QGIPVL1CM7VSECP5
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/pos/vnpay-callback