spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Table_Bee;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update         # dev thôi; prod dùng migration
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    open-in-view: false
