# App name
spring.application.name=beemate

# Ket noi MS SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=beemate1;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG
spring.web.resources.static-locations=classpath:/static/

# Mac dinh tieng Viet
spring.web.locale=vi_VN
spring.web.locale-resolver=fixed

#Cau hinh ngay thang
spring.mvc.format.date=dd/MM/yyyy
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.org.springframework.security=DEBUG

# T?ng gi?i h?n kích th??c request ?? nh?n ???c chu?i Base64 l?n
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# VNPay sandbox config
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/vnpay-return
vnpay.tmn-code=4YUP19I4
vnpay.secret-key=MDUIFDCRAKLNBPOFIAFNEKFRNMFBYEPX
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

# Cho phép Jackson b? qua các bean tr?ng/proxy c?a Hibernate
spring.jackson.serialization.fail-on-empty-beans=false

logging.level.root=WARN
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.transaction=DEBUG

server.error.include-message=always


cloudinary.cloud-name=dygj3spwt
cloudinary.api-key=979376284138992
cloudinary.api-secret=HdMhK5dGHtNN79JrPDTeRyntxm8

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true




